name: Infrastructure Deployment

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    name: Terraform settings
    runs-on: ubuntu-22.04
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Terraform version
      run: terraform version
